/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class CaConsultasEntrada extends javax.swing.JDialog {

    /**
     * Creates new form FoAdicionarAlunos
     */
    
    private Conexao c;
    private Integer Consulta;
    private Integer SelectCodConsulta = Consulta;
    
    public CaConsultasEntrada(Integer Consulta) {
        initComponents();
        this.setModal(true);
        this.c = new Conexao();
        this.Consulta = Consulta;
        
        
    //Carregar combobox
        this.c.setComboBox(CBMedico, "Medico");
        this.c.setComboBox(CBPaciente, "Paciente");
    
    
    //Edição
        if (Consulta!=-1) {
            this.setTitle("Editar");
            btnCadastrar.setText("Editar");
            
            //Carregar os campos
            try {
                String SQL = " SELECT C.Consulta,C.DataConsulta,M.Nome,P.Nome,C.Observacoes FROM Consulta as C INNER JOIN Paciente as P ON C.CodPaciente = P.CodPaciente INNER JOIN Medico as M ON C.CodMedico = M.CodMedico WHERE C.Consulta = "+Consulta;
                this.c.setResultSet(SQL);
                this.c.getResultSet().first();
                txtDataConsulta.setText(this.c.getResultSet().getString("C.DataConsulta"));  
                CBMedico.setSelectedItem(this.c.getResultSet().getString("M.Nome"));
                CBPaciente.setSelectedItem(this.c.getResultSet().getString("P.Nome"));
                txtObserv.setText(this.c.getResultSet().getString("C.Observacoes"));
            }
            catch(SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblObserv = new javax.swing.JLabel();
        txtObserv = new javax.swing.JTextField();
        txtDataConsulta = new javax.swing.JFormattedTextField();
        btnNovoMedico = new javax.swing.JButton();
        btnNovoPaciente = new javax.swing.JButton();
        CBPaciente = new javax.swing.JComboBox<>();
        lblData = new javax.swing.JLabel();
        CBMedico = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        lblMedico = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar");

        lblObserv.setText("Observações");

        txtObserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservActionPerformed(evt);
            }
        });

        try {
            txtDataConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataConsultaActionPerformed(evt);
            }
        });

        btnNovoMedico.setText("Novo");
        btnNovoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoMedicoActionPerformed(evt);
            }
        });

        btnNovoPaciente.setText("Novo");
        btnNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPacienteActionPerformed(evt);
            }
        });

        CBPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPacienteActionPerformed(evt);
            }
        });

        lblData.setText("Data Consulta");

        CBMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBMedico.setSelectedItem(SelectCodConsulta);
        CBMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMedicoActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblMedico.setText("Médico");

        lblPaciente.setText("Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDataConsulta)
                    .addComponent(txtObserv, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CBPaciente, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                            .addComponent(lblData, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedico, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObserv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBMedico, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovoMedico)
                            .addComponent(btnNovoPaciente))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovoMedico)
                        .addGap(28, 28, 28)
                        .addComponent(btnNovoPaciente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblObserv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtObservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservActionPerformed

    private void btnNovoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoMedicoActionPerformed
        // TODO add your handling code here:
        new CaMedicosEntrada(-1).setVisible(true);
        //Carregar combobox
        this.c.setComboBox(CBMedico, "Medico");
    }//GEN-LAST:event_btnNovoMedicoActionPerformed

    private void btnNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPacienteActionPerformed
        // TODO add your handling code here:
        new CaPacientesEntrada(-1).setVisible(true);
        //Carregar combobox
        this.c.setComboBox(CBPaciente, "Paciente");
    }//GEN-LAST:event_btnNovoPacienteActionPerformed

    private void CBPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPacienteActionPerformed

    private void CBMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBMedicoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (txtDataConsulta.getText().equals("    -  -  ")) {
            JOptionPane.showMessageDialog(this, "Informar a Data da Consulta");
            txtDataConsulta.requestFocus();
        }
        else if (CBMedico.getSelectedItem()==null) {
            JOptionPane.showMessageDialog(this, "Selecione o Médico");
            CBMedico.requestFocus();
        }
        else if (CBPaciente.getSelectedItem()==null) {
            JOptionPane.showMessageDialog(this, "Selecione o Paciente");
            CBPaciente.requestFocus();
        }
        else {       
            String SQL;
            String Msg;
            
            //Cadastrar
            if (this.Consulta == -1) {
                Msg = "Registro adicionado com sucesso";
                SQL = "INSERT INTO Consulta (DataConsulta,CodMedico,CodPaciente,Observacoes) VALUES ('"+ txtDataConsulta.getText() +"','"+this.c.getCodigoComboBox(CBMedico,"Medico")+"','"+this.c.getCodigoComboBox(CBPaciente,"Paciente")+"','"+txtObserv.getText()+"')";
            }                                                                                                                       
            //Editar
            else {
                Msg = "Registro editado com sucesso";
                SQL = "UPDATE Consulta SET DataConsulta = '"+txtDataConsulta.getText()+"',CodMedico = '"+this.c.getCodigoComboBox(CBMedico, "Medico")+"',CodPaciente = '"+this.c.getCodigoComboBox(CBPaciente, "Paciente")+"',Observacoes = '"+txtObserv.getText()+"' WHERE Consulta = "+Consulta;                              
            }
            this.c.SQLExecute(SQL);
            JOptionPane.showMessageDialog(this, Msg);
            this.dispose();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtDataConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataConsultaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBMedico;
    private javax.swing.JComboBox<String> CBPaciente;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnNovoMedico;
    private javax.swing.JButton btnNovoPaciente;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblObserv;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JFormattedTextField txtDataConsulta;
    private javax.swing.JTextField txtObserv;
    // End of variables declaration//GEN-END:variables
}
