/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */

public class FoSenha extends javax.swing.JFrame {

    /**
     * Creates new form FoSenha
     */
    
    private Conexao c;
    private String NomeUsuario;
    
    public FoSenha(String NomeUsuario) {
        initComponents();
        this.c = new Conexao();
        this.NomeUsuario = NomeUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenhaOrg = new javax.swing.JLabel();
        lblSenhaNv = new javax.swing.JLabel();
        lblSenhaNvC = new javax.swing.JLabel();
        btnSenha = new javax.swing.JButton();
        txtSenhaOrg = new javax.swing.JPasswordField();
        txtSenhaNv = new javax.swing.JPasswordField();
        txtSenhaNvC = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSenhaOrg.setText("Senha Atual:");

        lblSenhaNv.setText("Nova Senha:");

        lblSenhaNvC.setText("Confirmar Nova Senha:");

        btnSenha.setText("Alterar Senha");
        btnSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSenhaOrg)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenhaNv)
                            .addComponent(lblSenhaNvC))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSenhaOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSenhaNv, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSenhaNvC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblSenhaOrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenhaOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenhaNv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaNv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenhaNvC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaNvC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSenha)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenhaActionPerformed
        // TODO add your handling code here:
        if (txtSenhaOrg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informar a Senha Original");
            txtSenhaOrg.requestFocus();
        }
        else if (txtSenhaNv.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informar a Nova Senha");
            txtSenhaNv.requestFocus();
        }
        else if (txtSenhaNvC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informar a Nova Senha Novamente");
            txtSenhaNvC.requestFocus();
        }
        else if (!txtSenhaNv.getText().equals(txtSenhaNvC.getText())){
            JOptionPane.showMessageDialog(this, "Os campos nova senha e confirmar senha estão diferentes");
            txtSenhaNv.requestFocus();
            txtSenhaNv.setText("");
            txtSenhaNvC.setText("");
            txtSenhaOrg.setText("");
        }
        else if (txtSenhaNv.getText().length()<6){
            JOptionPane.showMessageDialog(this, "Nova senha deve conter no mínimo seis caracteres");
            txtSenhaNv.requestFocus();
            txtSenhaNv.setText("");
            txtSenhaNvC.setText("");
            txtSenhaOrg.setText("");
        }
        else{
            try{
                String SQL = " SELECT Senha FROM Usuario WHERE Nome = '" + NomeUsuario + "'";
                this.c.setResultSet(SQL);
                this.c.getResultSet().first();
                String SenhaAntiga = this.c.getResultSet().getString("Senha");
                if(!SenhaAntiga.equals(txtSenhaOrg.getText())){
                    JOptionPane.showMessageDialog(this, "Senha atual incorreta");
                    txtSenhaOrg.requestFocus();
                    txtSenhaNv.setText("");
                    txtSenhaNvC.setText("");
                    txtSenhaOrg.setText("");
                }
                else{
                    String SQL2;
                    String Msg;

                    //Editar
                    Msg = "Senha editada com sucesso";
                    SQL2 = "UPDATE Usuario SET Senha = '"+txtSenhaNv.getText()+"' WHERE Nome = '" + NomeUsuario + "'";                             
                    this.c.SQLExecute(SQL2);
                    JOptionPane.showMessageDialog(this, Msg);
                    this.dispose();
                }
            }
            catch(SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoSenha("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSenha;
    private javax.swing.JLabel lblSenhaNv;
    private javax.swing.JLabel lblSenhaNvC;
    private javax.swing.JLabel lblSenhaOrg;
    private javax.swing.JPasswordField txtSenhaNv;
    private javax.swing.JPasswordField txtSenhaNvC;
    private javax.swing.JPasswordField txtSenhaOrg;
    // End of variables declaration//GEN-END:variables
}
