/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;
import BackEnd.Conexao;

public class Main extends javax.swing.JFrame {

     private Conexao c;
     String NomeUsuario = null;
    /**
     * Creates new form Main
     */
    public Main() {
        int c;
        initComponents();
        this.c = new Conexao();
        FoLogin f = new FoLogin();
        f.setVisible(true);
        
        //Alterar título aplicação
        this.setTitle("Sistema Y - Usuário logado: " + f.getNomeUsuario());   
        NomeUsuario = f.getNomeUsuario();
    }
    
    public boolean ListMedico(){
        return this.c.setResultSet("SELECT * FROM Medico M;");
    }
    
    public boolean DetailMedico(Integer Id){
        if(Id == null){
            return false;
        }
        else{
            return this.c.setResultSet("SELECT * FROM Medico M WHERE CodMedico = "+Id);
        }
    }
    
    public boolean InsertMedico(String Nome){
        if (Nome == null){
            return false;
        }
        else if (Nome == ""){
            return false;
        }
        else{
            return this.c.SQLExecute("INSERT INTO Medico (Nome) VALUES('"+ Nome +"')");
        } 
    }
    
    public boolean UpdateMedico(Integer Id, String NomeNovo){
        if (NomeNovo == null || Id == null ){
            return false;
        }
        else if (NomeNovo == ""){
            return false;
        }
        else{
            return this.c.SQLExecute("UPDATE Medico SET Nome = '"+ NomeNovo +"'WHERE CodMedico="+ Id);
        } 
    }
    
    public boolean DeleteMedico(Integer Id){
        if (Id == null ){
            return false;
        }
        else{
            return this.c.SQLExecute("DELETE FROM Medico WHERE CodMedico = '"+ Id +"'");
        }
    }
    
    public boolean InsertPaciente(String Nome, String CPF, String Celular, String Endereco){
        if (Nome == null || CPF == null || Celular == null || Endereco == null){
            return false;
        }
        else if (Nome == "" || CPF == "" || Celular == "" || Endereco == ""){
            return false;
        }
        else{
            return this.c.SQLExecute("INSERT INTO Paciente (Nome,CPF,Celular,Endereco) VALUES('"+Nome+"','"+CPF+"','"+Celular+"','"+Endereco+"')");
        } 
    }
    
    public boolean UpdatePaciente(Integer Id,String Nome, String CPF, String Celular, String Endereco){
        if (Id == null || Nome == null || CPF == null || Celular == null || Endereco == null){
            return false;
        }
        else if (Nome == "" || CPF == "" || Celular == "" || Endereco == ""){
            return false;
        }
        else{
            return this.c.SQLExecute("UPDATE Paciente SET Nome = '"+ Nome +"', CPF = '"+CPF+"',Celular = '"+Celular+"', Endereco = '"+Endereco+"' WHERE CodPaciente="+Id);
        } 
    }
    
    public boolean DeletePaciente(Integer Id){
        if (Id == null ){
            return false;
        }
        else{
            return this.c.SQLExecute("DELETE FROM Paciente WHERE CodPaciente = '"+ Id +"'");
        }
    }
    
    public boolean InsertUsuario(String Nome, String CPF){
        if (Nome == null || CPF == null){
            return false;
        }
        else if (Nome == "" || CPF == ""){
            return false;
        }
        else{
            return this.c.SQLExecute("INSERT INTO Usuario (Nome,CPF,Senha) VALUES('"+Nome+"','"+CPF+"','"+CPF+"')");
        } 
    }
    
    public boolean UpdateUsuario(Integer Id,String Nome, String CPF, String Senha){
        if (Id == null || Nome == null || CPF == null || Senha == null){
            return false;
        }
        else if (Nome == "" || CPF == "" || Senha == ""){
            return false;
        }
        else{
            return this.c.SQLExecute("UPDATE Usuario SET Nome = '"+ Nome +"', CPF = '"+CPF+"',Senha = '"+Senha+"' WHERE CodUsuario="+Id);
        } 
    }
    
    public boolean DeleteUsuario(Integer Id){
        if (Id == null ){
            return false;
        }
        else{
            return this.c.SQLExecute("DELETE FROM Usuario WHERE CodUsuario = '"+ Id +"'");
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MnMain = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnCadastro = new javax.swing.JMenu();
        jMenuMedico = new javax.swing.JMenuItem();
        jMenuPaciente = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        jMenuItem1.setText("Editar Senha");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        MnMain.add(jMenu1);

        MnCadastro.setText("Cadastros");

        jMenuMedico.setText("Medicos");
        jMenuMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMedicoActionPerformed(evt);
            }
        });
        MnCadastro.add(jMenuMedico);

        jMenuPaciente.setText("Pacientes");
        jMenuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPacienteActionPerformed(evt);
            }
        });
        MnCadastro.add(jMenuPaciente);

        jMenuUsuario.setText("Usuarios");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        MnCadastro.add(jMenuUsuario);

        jMenuConsultas.setText("Consultas");
        jMenuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultasActionPerformed(evt);
            }
        });
        MnCadastro.add(jMenuConsultas);

        MnMain.add(MnCadastro);

        setJMenuBar(MnMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMedicoActionPerformed
        // TODO add your handling code here:
        new CaMedicos().setVisible(true);
    }//GEN-LAST:event_jMenuMedicoActionPerformed

    private void jMenuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPacienteActionPerformed
        // TODO add your handling code here:
        new CaPacientes().setVisible(true);
    }//GEN-LAST:event_jMenuPacienteActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        // TODO add your handling code here:
        new CaUsuarios().setVisible(true);
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultasActionPerformed
        // TODO add your handling code here:
        new CaConsultas().setVisible(true);
    }//GEN-LAST:event_jMenuConsultasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        new FoSenha(NomeUsuario).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnCadastro;
    private javax.swing.JMenuBar MnMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuConsultas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuMedico;
    private javax.swing.JMenuItem jMenuPaciente;
    private javax.swing.JMenuItem jMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
